# Generated by Django 6.0.4 on 2026-06-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Жанр'),
            preserve_default=False,
        ),
    ]
